version: '2'
services:
  node:
    build: .
    volumes:
      - .:/home/node
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    #command: "npm run debug"
    environment: 
      DNS_SERVER: 192.168.1.1

networks:
  default:
    external:
      name: dnsdock
