version: '2'
services:
  node:
    build: .
    image: docker.quisapps.com/dnsdock-node
    volumes:
      - .:/home/node
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    #command: "npm run debug"
    environment: 
      DNS_SERVER: 192.168.1.1
    container_name: dnsdock

networks:
  default:
    external:
      name: dnsdock
